### ISSUE TITLE
Global allele frequency map

### ISSUE THREAD

**Issue by onebeingmay** [aabiddanda/geovar#2]
Hello Arjun,
After reading your nice paper (https://elifesciences.org/articles/60107) and tutorial I am wondering if this package supports generation of global allele frequency map like Fig2C in your paper? I did not see such plot in your tutorial.
Thank you!

**Comment by aabiddanda** [comment]
Hi @onebeingmay, 

Thanks so much for the interest. The maps from figure 2C were based off of the [Geography of Genetic Variants browser](https://popgen.uchicago.edu/ggv/) hosted by the Novembre Lab (Marcus and Novembre 2018 Bioinfomatics). They offer a PDF export function for most variants. 

They're always trying to improve the browser as well - so any feedback to them would be helpful!

**Comment by aabiddanda** [comment]
Closing the issue as the main question has been answered.

**Comment by onebeingmay** [comment]
Thank you so much Arjun. It's a nice tool.
Best,
Wenbin

Arjun Biddanda ***@***.***> 于2022年4月24日周日 08:35写道：
