### ISSUE TITLE
Missing files when installing using pip?

### ISSUE THREAD

**Issue by blaiseli** [aabiddanda/geovar#4]
Hello,

I tried to install geovar in a virtual environment as follows:

```
pip install git+https://github.com/aabiddanda/geovar
```

The installation process reports no error.

However, if I try to import geovar in my jupyter notebook (that was started from my virtual env, and after restarting the kernel), I get an error message `ModuleNotFoundError: No module named 'geovar'`.

When I try on the command line (with the virtual env activated) same issue:

```
(.venv) bli@latimeria:/data/17537_Spaeth$ python3 -m geovar
/data/17537_Spaeth/.venv/bin/python3: No module named geovar
```

There is a folder for geovar in my `site-package` folder, but it seems that some important files are missing:

```
> (.venv) bli@latimeria:/data/17537_Spaeth$ ls -lhrt .venv/lib/python3.10/site-packages/geovar-0.1.dist-info/
> total 60K
> -rw-r--r-- 1 bli bli  92 Aug 13 14:51 WHEEL
> -rw-r--r-- 1 bli bli   1 Aug 13 14:51 top_level.txt
> -rw-r--r-- 1 bli bli   0 Aug 13 14:51 REQUESTED
> -rw-r--r-- 1 bli bli 641 Aug 13 14:51 RECORD
> -rw-r--r-- 1 bli bli 874 Aug 13 14:51 METADATA
> -rw-r--r-- 1 bli bli 35K Aug 13 14:51 LICENSE.md
> -rw-r--r-- 1 bli bli   4 Aug 13 14:51 INSTALLER
> -rw-r--r-- 1 bli bli 132 Aug 13 14:51 direct_url.json
```

In particular, there is no `__init__.py` file.

This is unusual.

**Comment by aabiddanda** [comment]
Hello @blaiseli , thanks for bringing this to my attention and sorry for the lateness in getting back to you! I just tried the following and was able 

```
mkdir geovar_test
pyenv virtualenv 3.7.6 geovar_test
pyenv local geovar_test
git clone git@github.com:aabiddanda/geovar.git
cd geovar/; pip install .
cd ..
mkdir test/
cd test/
ipython

In [1]: import geovar
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-a08541a19fb8> in <module>
----> 1 import geovar

ModuleNotFoundError: No module named 'geovar'
``` 

So yes you are correct that the `__init__.py` is not getting propagated through. I've added a fix `setup.cfg` in the most recent commit (8f19175df995b01f7dc4e7277cf26a7f6a786f54) that eliminated this error and allowed me to run the notebook from a separate directory.

**Comment by aabiddanda** [comment]
@blaiseli could you please try to install from the most recently tagged version (0.1.1) https://github.com/aabiddanda/geovar/releases/tag/v0.1.1 and confirm that this fixes your error? I'll then close the issue. 

Also feel free to put in other issues if you are planning on using the software. I'm planning a v0.2 release in the next month with some improved testing and some refactoring of the original code.

**Comment by blaiseli** [comment]
@aabiddanda Thanks for the quick fix. I haven't tested the library, but the module import works now.

Note that `geovar.__version__` is currently set to '0.1.0'
