### ISSUE TITLE
MAC MAF 0 after converting vcf to freq table.

### ISSUE THREAD

**Issue by nitinra** [aabiddanda/geovar#7]
Hello,

I am trying to use geovar to look at allele freq changes among my populations.

Here is my script that I used: [geovar_test.txt](https://github.com/aabiddanda/geovar/files/9977265/geovar_test.txt), my population file: [ella2.txt](https://github.com/aabiddanda/geovar/files/9977267/ella2.txt), my [vcf file](https://drive.google.com/file/d/1YsbbnHyotYGVz7s08Xqn9LSLkxXsTVI4/view?usp=sharing) and the [output file](https://drive.google.com/file/d/1U-wy_EflTsuKlQGra7FwyQmQ-jpf9hdb/view?usp=sharing). Can you please look into it and let me know what I am doing wrong? I was able to replicate the test data. 

The run is not throwing any error and hence I am not sure as to what the issue is.

Thanks a lot for your help!!

**Comment by nitinra** [comment]
Realized that my vcf file was empty! It works perfectly now! My apologies!

**Comment by aabiddanda** [comment]
@nitinra its also worth mentioning that `geovar` is currently not well-designed for variants that might be multi-allelic (e.g. STRs or complex indels). It's strange that the `AC` and `AF` tags are in the VCF but not the actual genotype calls (perhaps some oddity with GATK). 

Feel free to let me know via email or github issue if there are features you would find helpful in `geovar` as well! Best of luck!
