### ISSUE TITLE
geovar_codes_streaming() can not read gzipped file

### ISSUE THREAD

**Issue by kitchensjn** [aabiddanda/geovar#8]
Thanks for putting this package together!

I'm messing around with different binning cutoffs for data from the [Dryad repo](https://doi.org/10.5061/dryad.rjdfn2z7v), but ran into this error

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte`

with the `geovar_codes_streaming()` function. It appears that you can't pass the gzipped frequency files into this function due to how the function opens and reads the files. Since these larger compressed files are likely to require data streaming, I think that it would be helpful for this function to take gzipped files as inputs using gzip library as a dependency. It'll likely also require a check for whether the input file is gzipped or not, but everything else should remain essentially the same.

**Comment by aabiddanda** [comment]
Hi @kitchensjn , 

This is a great point. I have put in a short fix for this on the `gzip_streaming` branch just now actually. The main code update is in the following couple of lines: 

https://github.com/aabiddanda/geovar/blob/9562aac542c476bf70f738f8562e9802dda75c5a/geovar/binning.py#L100-L109

I'm going to create a couple of tests prior to merging this into `main` and marking this issue as closed, but will certainly let you know when to test out this functionality. One other option in my mind would be to directly pass in the file object to the method, like the following: 

```
geovar_obj = GeoVar()
...
with gzip.open(file.txt.gz, "rt") as gzf:
     geovar_obj.geovar_codes_streaming(gzf)
```

I think that the latter is slightly more elegant but requires the file-handling outside. Let me know if you prefer the latter option, but I can't imagine more than handling plaintext and gzipped files so it seems like the current solution should work well.

**Comment by aabiddanda** [comment]
Hi @kitchensjn - thanks very much for this suggestion! I've updated the newest release to now account for handling of gzipped files (along with some unit testing for those functions). Feel free to `pip install git+https://github.com/aabiddanda/geovar` to get the latest changes.

Closing this issue now as its been adequately addressed. Feel free to reopen if you feel that it is still buggy :)
